pipeline {
    agent any
    environment {
        PATH = "/opt/apache-maven-3.9.3-bin/apache-maven-3.9.3/bin:${env.PATH}"
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Complete') {
            steps {
                echo 'Job Complete!'
            }
        }
        stage('Last Step') {
            steps {
                echo 'Last step!'
            }
        }
        
    }
}
